根据标点和分词器处理长文本
fishaudio/Bert-VITS2 pull request #63
Opened 2023-10-13 03:27 UTC by ALEXuH

先使用标点进行初步切分，对于过长的在使用分词器，并且根据最后标点符号添加不同的静音长度

2023-10-13 06:28 UTC, jiangyuxiaoxiao requested changes
考虑到像`我去，初音未来...`这样带`...`的语句，正则改成r'([^,，.。?？!！]*[,，.。?？!！]+)'会不会好些，我还没有详细测试

2023-10-13 08:33 UTC, jiangyuxiaoxiao commented
> > 考虑到像`我去，初音未来...`这样带`...`的语句，正则改成r'([^,，.。?？!！]*[,，.。?？!！]+)'会不会好些，我还没有详细测试
> 
> 这种 ... 两种都是能正常匹配的，但是如果改成+对于 (我去初音未来) 这种一个标点都没有 或者没有包含的标点 （我去初||||音未来&&&|||||）这些就匹配不上了
刚才试了一下会被切成这个样子
![image](https://github.com/fishaudio/Bert-VITS2/assets/52267304/bbb87014-1fa2-476c-bd69-a8ac43ab42e9)，这样`...`就可能在很特殊的情况被切成两半（刚好跨过MAXLENGTH）。没有标点的情况确实更应该考虑，直接改成`+`不行。

2023-10-13 10:41 UTC, ALEXuH commented
> > > 考虑到像`我去，初音未来...`这样带`...`的语句，正则改成r'([^,，.。?？!！]*[,，.。?？!！]+)'会不会好些，我还没有详细测试
> > 
> > 
> > 这种 ... 两种都是能正常匹配的，但是如果改成+对于 (我去初音未来) 这种一个标点都没有 或者没有包含的标点 （我去初||||音未来&&&|||||）这些就匹配不上了
> > 刚才试了一下会被切成这个样子
> > ![image](https://github.com/fishaudio/Bert-VITS2/assets/52267304/bbb87014-1fa2-476c-bd69-a8ac43ab42e9)，这样`...`就可能在很特殊的情况被切成两半（刚好跨过MAXLENGTH）。没有标点的情况确实更应该考虑，直接改成`+`不行。

确实，不过这个感觉不影响音频结果，针对这种情况可以暴力一点，做个前置处理，把 ... 统一替换成一个字符 。

2023-10-15 07:34 UTC, leng-yue commented
其实我这个分词代码有处理, 你们可以参考的 (
https://github.com/fishaudio/Bert-VITS2/blob/6d7725de369dfc372b3bc2c394335984bc645889/text/parser.py#L130

2023-10-18 01:57 UTC, closed without merging