主要：多说话人分段合成，次要: WebUi
fishaudio/Bert-VITS2 pull request #67
Opened 2023-10-15 12:06 UTC by AnyaCoder

最主要的特性就是多说话人多语言合成，将webui界面（训练的all_process.py和推理webui.py(附带正则匹配re_matching.py)）做得更人性化，加入信息提示。除此以外都是我额外加入的单机单卡的训练代码(all_process.py,asr_transcript.py,extern_subprocess.py)。在其他人克隆这个项目时，原先的master分支代码仍可以正常执行。

2023-10-16 09:01 UTC, jiangyuxiaoxiao requested changes

2023-10-16 09:48 UTC, AnyaCoder commented on webui.py
了解了，我会在dev上改动

2023-10-18 01:55 UTC, Stardust-minus commented
请push到dev-webui分支，其余冲突我会解决

2023-10-18 09:08 UTC, Stardust-minus commented
已经合并

2023-10-18 09:08 UTC, closed without merging